In [1]:
import pandas as pd
import numpy as np

In [2]:
og = pd.read_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\IDS-DRR-Assam\Dashboards\Flood Tenders Dashboard\sqllab_query_assam_flood_tenders_20240930T091542.csv')
og

,s_no,tender_id,tender_externalreference,tender_title,work_description,tender_category,tender_type,form_of_contract,product_category,is_multi_currency_allowed_for_boq,...,tender_block,tender_subdistrict,tender_revenueci,tender_revenueci_location,hq_flag,revenue_circle_finalised,rc_from_internet_sources,rc_manual_tagging_status,rc_old_data,district_old_data
0,11,2018_DoWR_6310_2,HAILAKANDI/RIDF-XXIII/1,A E Measures to Protect Sahabad-Rongpur area,Anti Erosion Measures to Protect Sahabad-Rongp...,Works,Open Tender,Works,Civil Works,No,...,HAILAKANDI,Hailakandi,Hailakandi,Hailakandi,True,Hailakandi,NaN,NaN,NaN,NaN
1,127,2019_DoWR_11627_1,HAILAKANDI/2018-19/SDRF/IV,IM FROM MOHANPUR TO CONFLUENCE,IMMEDIATE MEASURES TO DYKE ALONG L/B OF RIVER ...,Works,Open Tender,Works,Civil Works,No,...,HAILAKANDI,Hailakandi,Hailakandi,Hailakandi,True,Hailakandi,NaN,NaN,NaN,NaN
2,141,2019_DoWR_11622_1,HAILAKANDI/2018-19/SDRF/V,IM to protect Nandigram Area,Immediate measures to protect Nandigram area f...,Works,Open Tender,Works,Civil Works,No,...,HAILAKANDI,Hailakandi,Hailakandi,Hailakandi,True,Hailakandi,NaN,NaN,NaN,NaN
3,151,2019_DoWR_11496_1,HAILAKANDI/2018-19/SDRF/II,IM at Matijuri,Immediate measures to Restoration for damages ...,Works,Open Tender,Works,Civil Works,No,...,HAILAKANDI,Hailakandi,Hailakandi,Hailakandi,True,Hailakandi,NaN,NaN,NaN,NaN
4,268,2019_DoWR_11623_1,HAILAKANDI/2018-19/SDRF/VI,IM from Mahadev Tilla to Rupacherra Bunglow Tilla,Immediate measures to dyke along R/b of river ...,Works,Open Tender,Works,Civil Works,No,...,HAILAKANDI,Hailakandi,Hailakandi,Hailakandi,True,Hailakandi,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2363,2294,2021_PWD_22958_1,EE/JDTTRD/SDRF/NIT/328,Reconstruction of flood damaged at T06 to Sris...,Reconstruction of flood damaged at T06 to Sris...,Works,Open Tender,Item Rate,Civil Works – Roads,No,...,NaN,NaN,NaN,NaN,False,Jorhat East,NaN,NaN,Jorhat East,JORHAT
2364,2303,2020_DoWR_16825_2,TEZPUR/2019-20/SOPD-FDR/III,Anti erosion measures to protect Biswanath Gha...,Anti erosion measures to protect Biswanath Gha...,Works,Open Tender,Works,Civil Works,No,...,NaN,NaN,NaN,NaN,False,Biswanath,NaN,NaN,Biswanath,BISWANATH
2365,2318,2020_DoWR_16600_1,NALBARI/2019-20/SOPD-FDR/III,Reconstruction of breached like damage embankm...,Reconstruction of breached like damage embankm...,Works,Open Tender,Works,Civil Works,No,...,NaN,NaN,NaN,NaN,False,Ghograpar (Pt),NaN,NaN,Ghograpar,NALBARI
2366,2330,2020_DoWR_17137_1,JOR/SDRF/GELABEEL/2019-20/1,Immediate measures to restore Namtemera area f...,Immediate measures to restore Namtemera area f...,Works,Open Tender,Works,Civil Works,No,...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,JORHAT
2367,2350,2020_DoWR_16357_1,SILCHAR/2019-20/SOPD-FDR/III,Reconstruction of almost Breached embankment a...,Reconstruction of almost Breached embankment a...,Works,Open Tender,Works,Civil Works,No,...,NaN,NaN,NaN,NaN,False,Silchar,NaN,NaN,Silchar,CACHAR

In [20]:
update = pd.read_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\IDS-DRR-Assam\Dashboards\Flood Tenders Dashboard\floodtenders_RCgeotagged.csv')
update.columns = update.columns.str.lower().str.replace(' ', '_')
update = update.rename(columns={'contract_date_:':'contract_date','bid_validity(days)':'bid_validity_days','tender_value_in_₹':'tender_value_in_rupees'})
update['tender_value_in_rupees'] = update['tender_value_in_rupees'].str.replace(',', '')
update['tender_value_in_rupees'] = update['tender_value_in_rupees'].astype(float)
update = update.dropna(subset=['awarded_value', 'tender_value_in_rupees','district_finalised'])
update['awarded_value'] = update['awarded_value'].str.replace(',', '')
update['awarded_value'] = update['awarded_value'].astype(float)
update

,unnamed:_0,tender_id,tender_externalreference,tender_title,work_description,tender_category,tender_type,form_of_contract,product_category,is_multi_currency_allowed_for_boq,...,tender_district_location,btc_flag,district_finalised,tender_villages,tender_block,tender_subdistrict,tender_revenueci,tender_revenueci_location,hq_flag,revenue_circle_finalised
0,159,2017_DoWR_2083_1,Hailakandi/SDRF/2016-17/2,Dhaleswari Katakhal 1,Immediate measures to improvement of Dhaleswar...,Works,Open Tender,Works,Civil Works,No,...,HAILAKANDI,False,HAILAKANDI,NaN,HAILAKANDI,Hailakandi,Hailakandi,Hailakandi,True,Hailakandi
1,160,2017_DoWR_2238_1,Hailakandi/SDRF/2016-17/2,Dhaleswari Katakhal Drainage Basin Ph-II,Immediate measures to improvement of Dhaleswar...,Works,Open Tender,Works,Civil Works,No,...,HAILAKANDI,False,HAILAKANDI,NaN,HAILAKANDI,Hailakandi,Hailakandi,Hailakandi,True,Hailakandi
2,210,2018_DoWR_5796_1,HAILAKANDI/SDRF/2017-18/1,IM at Kalinagar Pk-1,Immediate measures to dyke along l/b of river ...,Works,Open Tender,Works,Civil Works,No,...,HAILAKANDI,False,HAILAKANDI,"'MOHANPUR', 'KALINAGAR'",HAILAKANDI,Hailakandi,Hailakandi,Hailakandi,True,Hailakandi
3,372,2018_DoWR_6310_2,HAILAKANDI/RIDF-XXIII/1,A E Measures to Protect Sahabad-Rongpur area,Anti Erosion Measures to Protect Sahabad-Rongp...,Works,Open Tender,Works,Civil Works,No,...,HAILAKANDI,False,HAILAKANDI,"'SAHABAD', 'RONGPUR', 'Rongpur'",HAILAKANDI,Hailakandi,Hailakandi,Hailakandi,True,Hailakandi
4,552,2019_DoWR_11496_1,HAILAKANDI/2018-19/SDRF/II,IM at Matijuri,Immediate measures to Restoration for damages ...,Works,Open Tender,Works,Civil Works,No,...,HAILAKANDI,False,HAILAKANDI,"'MATIJURI', 'Matijuri'",HAILAKANDI,Hailakandi,Hailakandi,Hailakandi,True,Hailakandi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2691,2637,2024_DoWR_36038_1,MAJULI/2023-24/NIDA/I,Protection of Pekamoni and its adjoining areas...,Protection of Pekamoni and its adjoining areas...,Works,Open Tender,Works,Civil Works,No,...,MAJULI,False,CONFLICT,NaN,NaN,NaN,NaN,NaN,False,NaN
2692,2645,2024_DoWR_36137_1,CACHAR/2023-24/NIDA/III,Anti-Erosion Measures to Protect of new Law Co...,Anti-Erosion Measures to Protect of new Law Co...,Works,Open Tender,Works,Civil Works,No,...,CACHAR,False,CONFLICT,NaN,NaN,NaN,NaN,NaN,False,NaN
2693,2673,2023_SCD_34601_8,Tender/NIT/Pt/2023-24/7736,EARTHEN EMBANKMENT/GUIDE BUND AT MORAN CHUTIA ...,EARTHEN EMBANKMENT/GUIDE BUND AT MORAN CHUTIA ...,Works,Open Tender,Item Rate,Civil Works,No,...,JORHAT,False,CONFLICT,NaN,NaN,NaN,NaN,NaN,False,NaN
2694,2680,2024_DoWR_36023_2,GOLAGHAT/2023-24/NIDA/I,Anti erosion measures to protect Amguri Basapa...,Anti erosion measures to protect Amguri Basapa...,Works,Open Tender,Works,Civil Works,No,...,GOLAGHAT,False,CONFLICT,NaN,NaN,NaN,NaN,NaN,False,NaN
2695,2682,2024_DoWR_36478_1,DHEMAJI/2023-24/NIDA/II,Extension of Gainadi L/B embankment from Sumon...,Extension of Gainadi L/B embankment from Sumon...,Works,Open Tender,Works,Civil Works,No,...,DHEMAJI,False,CONFLICT,NaN,NaN,NaN,NaN,NaN,False,NaN

In [19]:
update.to_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\IDS-DRR-Assam\Dashboards\Flood Tenders Dashboard\floodtenders_2017-24.csv')